# Generated by Django 4.0.4 on 2022-09-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_tracker', '0002_auto_20201018_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='errormodel',
            name='exception_text',
            field=models.CharField(default=0, max_length=1256),
            preserve_default=False,
        ),
    ]
